### ISSUE TITLE
Employee Searching Problem Case Sensitive

### ISSUE THREAD

**Issue by joypaul1** [Rangs-Group/hr_apps_api#1]
can we do this  like this
LOWER(U.RML_ID) LIKE LOWER('%$SEARCH_DATA%')
OR LOWER(U.MAIL) LIKE LOWER('%$SEARCH_DATA%')
OR LOWER(U.DESIGNATION) LIKE LOWER('%$SEARCH_DATA%')
OR LOWER(U.EMP_NAME) LIKE LOWER('%$SEARCH_DATA%')
OR LOWER(U.DEPT_NAME) LIKE LOWER('%$SEARCH_DATA%')
OR LOWER(U.MOBILE_NO) LIKE LOWER('%$SEARCH_DATA%')

**Comment by joypaul1** [comment]
Solve this 
 LOWER(U.RML_ID) LIKE LOWER('%$SEARCH_DATA%')
                                OR LOWER(U.MAIL) LIKE LOWER('%$SEARCH_DATA%')
                                OR LOWER(U.DESIGNATION) LIKE LOWER('%$SEARCH_DATA%')
                                OR LOWER(U.EMP_NAME) LIKE LOWER('%$SEARCH_DATA%')
                                OR LOWER(U.DEPT_NAME) LIKE LOWER('%$SEARCH_DATA%')
                                OR LOWER(U.MOBILE_NO) LIKE LOWER('%$SEARCH_DATA%')

**Comment by RangsGroup** [comment]
It's working fine now.
